server:
  port: 8887

spring:
  application:
    name: EmPersistenceService
  security:
    enabled: false
    user:
      name: admin
      password: abnamro
  h2:
    console:
      enabled: true
  datasource:
    initialize: true
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

api:
  key: em-persistence-api-key